# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOUMgfRHv6GUoFua6E0vZovK7YENPx-n
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

passengerld = df["PassengerId"].to_numpy()
print(passengerld)

survived = df["Survived"].to_numpy()
print(survived)

pclass = df["Pclass"].to_numpy()
print(pclass)

name = df["Name"].to_numpy()
print(name)

sex = df["Sex"].to_numpy()
print(sex)

age = df["Age"].to_numpy()
print(age)

sibsp = df["sibSp"].to_numpy()
print(sinsp)

parch = df["Parch"].to_numpy()
print(parch)

ticket = df["Ticket"].to_numpy()
print(ticket)

fare = df["Fare"].to_numpy()
print(fare)

cabin = df["Cabin"].to_numpy()
print(cabin)

embarked = df["Embarked"].to_numpy()
print(embarked)

print("First 5 rows of the DataFrame:")
print(df.head())

print("\nConcise summary of the DataFrame:")
df.info()

print("\nDescriptive statistics of the DataFrame:")
print(df.describe())

print("Missing values before handling:")
print(df.isnull().sum())

# Fill missing 'Age' values with the mean
age_mean = df['Age'].mean()
df['Age'].fillna(age_mean, inplace=True)

# Fill missing 'Embarked' values with the mode
embarked_mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(embarked_mode, inplace=True)

print("\nMissing values after filling 'Age' and 'Embarked':")
print(df.isnull().sum())

age_series = df['Age']
fare_series = df['Fare']
survived_series = df['Survived']

print("Age Series:\n", age_series.head())
print("\nFare Series:\n", fare_series.head())
print("\nSurvived Series:\n", survived_series.head())

df.rename(columns={'Sex': 'Gender'}, inplace=True)
print("Updated DataFrame columns:")
print(df.columns)

"""## Indexing and Slicing

### Subtask:
Demonstrate how to retrieve specific passenger details and extract columns using `.loc[]` and `.iloc[]`.

"""

print("DataFrame columns to identify .iloc positions:")
print(df.columns)

# 1. Use .loc[] to retrieve specific passenger details
specific_passengers_loc = df.loc[df['PassengerId'].isin([2, 4]), ['Name', 'Age', 'Fare']]

# 2. Use .iloc[] to extract data for the first 5 rows and specific columns
# Columns: 'Pclass' (index 2), 'Age' (index 5), 'Fare' (index 9)
specific_passengers_iloc = df.iloc[0:5, [2, 5, 9]]

# 3. Print both DataFrames
print("\nSpecific passengers using .loc[]:")
print(specific_passengers_loc)

print("\nSpecific passengers using .iloc[]:")
print(specific_passengers_iloc)

import pandas as pd

# 1. Filter for passengers with 'Age' > 30
age_filtered_df = df[df['Age'] > 30]

# 2. Filter for passengers with 'Fare' > 50
fare_filtered_df = df[df['Fare'] > 50]

# 3. Filter for female passengers who survived
female_survivors_df = df[(df['Gender'] == 'female') & (df['Survived'] == 1)]

# 4. Sort the original df DataFrame by 'Fare' descending and 'Age' ascending
sorted_df = df.sort_values(by=['Fare', 'Age'], ascending=[False, True])

# 5. Print the head of each DataFrame
print("\nPassengers with Age > 30 (age_filtered_df):")
print(age_filtered_df.head())

print("\nPassengers with Fare > 50 (fare_filtered_df):")
print(fare_filtered_df.head())

print("\nFemale passengers who survived (female_survivors_df):")
print(female_survivors_df.head())

print("\nDataFrame sorted by Fare (desc) and Age (asc) (sorted_df):")
print(sorted_df.head())

import pandas as pd

# 1. Calculate survival rate by gender
survival_rate_by_gender = df.groupby('Gender')['Survived'].mean()

# 2. Calculate average age by passenger class
average_age_by_pclass = df.groupby('Pclass')['Age'].mean()

# 3. Calculate survival counts by embarked location
survival_counts_by_embarked = df.groupby('Embarked')['Survived'].sum()

# 4. Print the results
print("\nSurvival Rate by Gender:")
print(survival_rate_by_gender)

print("\nAverage Age by Passenger Class:")
print(average_age_by_pclass)

print("\nSurvival Counts by Embarked Location:")
print(survival_counts_by_embarked)

df_melted = pd.melt(df, id_vars=['PassengerId', 'Gender'], value_vars=['Age', 'Fare', 'Survived'])
print("First 5 rows of the melted DataFrame:")
print(df_melted.head())

"""## Merge/Concatenate DataFrames

### Subtask:
Create a small, additional DataFrame and then demonstrate how to combine it with the main Titanic DataFrame using `merge()` or `concat()` to simulate richer dataset integration.

**Reasoning**:
I will create a new DataFrame with 'PassengerId' and 'Nationality' columns, using existing passenger IDs from the main DataFrame to simulate additional data. Then, I will perform a left merge operation with the main 'df' DataFrame on the 'PassengerId' column and display the head of the merged DataFrame to show the new 'Nationality' column.
"""

import pandas as pd

# 1. Create a new DataFrame named additional_info_df
additional_info_df = pd.DataFrame({
    'PassengerId': [2, 4, 7, 11, 12],
    'Nationality': ['British', 'American', 'French', 'Canadian', 'German']
})

# 2. Merge the df DataFrame with additional_info_df
df_merged = pd.merge(df, additional_info_df, on='PassengerId', how='left')

# 3. Print the head of the df_merged DataFrame
print("First 5 rows of the merged DataFrame (df_merged):")
print(df_merged.head())

print("### Key Insights")

# 1. Calculate the average age for survivors and non-survivors
average_age_survived = df[df['Survived'] == 1]['Age'].mean()
average_age_not_survived = df[df['Survived'] == 0]['Age'].mean()

# 2. Determine the highest and lowest fare paid
highest_fare = df['Fare'].max()
lowest_fare = df['Fare'].min()

# 3. Calculate the overall survival percentage
overall_survival_percentage = (df['Survived'].sum() / len(df)) * 100

# 4. Print all calculated insights with descriptive labels
print(f"Average Age of Survivors: {average_age_survived:.2f} years")
print(f"Average Age of Non-Survivors: {average_age_not_survived:.2f} years")
print(f"Highest Fare Paid: ${highest_fare:.2f}")
print(f"Lowest Fare Paid: ${lowest_fare:.2f}")
print(f"Overall Survival Percentage: {overall_survival_percentage:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

print("Imported matplotlib.pyplot as plt and seaborn as sns.")

plt.figure(figsize=(15, 5))

# 1. Survival rate by Gender
plt.subplot(1, 3, 1)
sns.barplot(x='Gender', y='Survived', data=df, palette='viridis')
plt.title('Survival Rate by Gender')
plt.ylabel('Survival Rate')

# 2. Survival rate by Pclass
plt.subplot(1, 3, 2)
sns.barplot(x='Pclass', y='Survived', data=df, palette='viridis')
plt.title('Survival Rate by Passenger Class')
plt.ylabel('Survival Rate')

# 3. Survival rate by Embarked location
plt.subplot(1, 3, 3)
sns.barplot(x='Embarked', y='Survived', data=df, palette='viridis')
plt.title('Survival Rate by Embarked Location')
plt.ylabel('Survival Rate')

plt.tight_layout()
plt.show()

# 4. Age distribution for survivors vs non-survivors
plt.figure(figsize=(10, 6))
sns.kdeplot(df[df['Survived'] == 1]['Age'], label='Survived', fill=True, alpha=0.6)
sns.kdeplot(df[df['Survived'] == 0]['Age'], label='Not Survived', fill=True, alpha=0.6)
plt.title('Age Distribution for Survivors vs. Non-Survivors')
plt.xlabel('Age')
plt.ylabel('Density')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

print("Generated and displayed plots for survival patterns.")

plt.figure(figsize=(15, 5))

# 1. Survival rate by Gender
plt.subplot(1, 3, 1)
sns.barplot(x='Gender', y='Survived', data=df, palette='viridis', hue='Gender', legend=False)
plt.title('Survival Rate by Gender')
plt.ylabel('Survival Rate')

# 2. Survival rate by Pclass
plt.subplot(1, 3, 2)
sns.barplot(x='Pclass', y='Survived', data=df, palette='viridis', hue='Pclass', legend=False)
plt.title('Survival Rate by Passenger Class')
plt.ylabel('Survival Rate')

# 3. Survival rate by Embarked location
plt.subplot(1, 3, 3)
sns.barplot(x='Embarked', y='Survived', data=df, palette='viridis', hue='Embarked', legend=False)
plt.title('Survival Rate by Embarked Location')
plt.ylabel('Survival Rate')

plt.tight_layout()
plt.show()

# 4. Age distribution for survivors vs non-survivors
plt.figure(figsize=(10, 6))
sns.kdeplot(df[df['Survived'] == 1]['Age'], label='Survived', fill=True, alpha=0.6)
sns.kdeplot(df[df['Survived'] == 0]['Age'], label='Not Survived', fill=True, alpha=0.6)
plt.title('Age Distribution for Survivors vs. Non-Survivors')
plt.xlabel('Age')
plt.ylabel('Density')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

print("Generated and displayed plots for survival patterns.")